### ISSUE TITLE
RegEdit for UltraDMD

### ISSUE THREAD

**Issue by mkalkbrenner** [mkalkbrenner/dof_configtool_client#1]

**Comment by MKPinC** [comment]
Maintenance of the Ultra DMD settings would be nice.
It would fit to the ScreenRes.txt and dmddevice.ini settings under "Text Edit" Tab although it has to be maintained with regedit.

Anyway it's not a must have, as a comment line in ScreenRes.txt and/or dmddevice.ini would also help to find the required registry entry Computer\HKEY_CURRENT_USER\Software\UltraDMD

**Comment by mkalkbrenner** [comment]
FlexDMD is the new player in the game :-)

**Comment by mkalkbrenner** [comment]
Since FlexDMD simply uses freezy's DLL for rendering there's no special setting required anymore.
It makes no sence to thik about UltraDMD anymore if FelxDMD is the future.
