### ISSUE TITLE
auto tweak downloaded files

### ISSUE THREAD

**Issue by MKPinC** [mkalkbrenner/dof_configtool_client#66]
At http://configtool.vpuniverse.com there's a pull program (it's just a batch file) that can run on e.g. windows startup to get all new DOF effects automatically.

If I had tweaked a setting, eg increased default_effect_duration for the fan, each time the pull programm loads the new file, the tweak is lost.

A possiblity to extend this batch file and "auto tweak" the loaded files would be nice.

Or a completely new batch file for following steps in the DOF ConfigToolClient:
- start DOF ConfigToolClient
- Download 
- Tweak day+night and save

**Comment by mkalkbrenner** [comment]
I added multiple commands to the symfony console:
```
  dof:download                Download DOF ini files
  dof:download-and-tweak      Download and tweak DOF ini files
  dof:tweak                   Tweak DOF ini files
```
